const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let D={projects:[],testimonials:[],messages:[],conversations:[],settings:{}};let activeChat=null;let sortBusy=false;let dragState=null;
async function api(url,opt={}){const r=await fetch(url,{credentials:'same-origin',...opt,headers:{'Content-Type':'application/json',...(opt.headers||{})}});const t=await r.text();let j={};try{j=t?JSON.parse(t):{}}catch{}if(!r.ok)throw Error(j.error||'Request failed');return j}
function toast(t){const e=$('#toast');e.textContent=t;e.style.display='block';clearTimeout(window.__toast);window.__toast=setTimeout(()=>e.style.display='none',2200)}
function tab(id){$$('.section').forEach(x=>x.classList.toggle('active',x.id===id));$$('.side-nav button[data-tab]').forEach(x=>x.classList.toggle('active',x.dataset.tab===id));const names={dashboard:'Dashboard',projects:'Projects / Case Studies',services:'Services',about:'About Me',skills:'Skills & Technologies',marquee:'Marquee Logos',process:'Process Steps',metrics:'Metrics & Stats',visualFlow:'Estimator',testimonials:'Testimonials',pages:'Blog / Articles',media:'Media Library',navigation:'Navigation',messages:'Contact Messages',chat:'Live Chat',payments:'Payments',transactions:'Transactions',withdraw:'Withdraw / Payouts',invoices:'Invoices',appearance:'Appearance',seo:'SEO Settings',analytics:'Analytics',hosting:'Domain & Hosting',general:'General Settings',users:'Users & Permissions',compare:'Compare Section',faq:'FAQ'};$('#pageTitle').textContent=names[id]||'Dashboard';$('#pageSubtitle').textContent=id==='dashboard'?'Welcome back, Ethon! 👋':'Manage '+(names[id]||'your website').toLowerCase();if(id==='messages')renderMessages();if(id==='chat')renderChats();if(id==='transactions')renderTransactions()}
const SITE_SECTION_META=[['hero','Home / Hero'],['marquee','Marquee / Logos'],['metrics','Metrics / Stats'],['about','About'],['estimator','Estimator'],['services','Services'],['compare','Compare'],['motion','Motion / Showreel'],['process','Process'],['work','Portfolio / Projects'],['testimonials','Testimonials'],['faq','FAQ'],['contact','Contact']];
function buildSiteSectionEditor(){const root=$('#siteSectionsEditor');if(!root)return;const s=D.settings||{};const order=Array.isArray(s.sectionOrder)?s.sectionOrder:SITE_SECTION_META.map(x=>x[0]);const vis=s.sectionVisibility||{};const keys=[...order,...SITE_SECTION_META.map(x=>x[0])].filter((x,i,a)=>SITE_SECTION_META.some(m=>m[0]===x)&&a.indexOf(x)===i);root.innerHTML=keys.map(k=>{const meta=SITE_SECTION_META.find(x=>x[0]===k);return `<div class="section-manager-row" draggable="true" data-section-key="${esc(k)}"><span class="section-manager-grip">☷</span><div><span class="section-manager-title">${esc(meta?meta[1]:k)}</span><span class="section-manager-key">#${esc(k)}</span></div><label class="section-manager-toggle"><input type="checkbox" class="section-manager-visible" ${vis[k]!==false?'checked':''}> Visible</label></div>`}).join('');bindSiteSectionSortable(root)}
function bindSiteSectionSortable(root){if(!root||root.dataset.bound)return;root.dataset.bound='1';let drag=null;root.addEventListener('dragstart',e=>{drag=e.target.closest('.section-manager-row');if(drag)drag.classList.add('dragging')});root.addEventListener('dragover',e=>{const target=e.target.closest('.section-manager-row');if(!drag||!target||target===drag)return;e.preventDefault();target.classList.add('drag-over');const r=target.getBoundingClientRect();root.insertBefore(drag,e.clientY<r.top+r.height/2?target:target.nextSibling)});root.addEventListener('drop',e=>{if(!drag)return;e.preventDefault();root.querySelectorAll('.drag-over').forEach(x=>x.classList.remove('drag-over'));drag.classList.remove('dragging');drag=null});root.addEventListener('dragend',()=>{root.querySelectorAll('.drag-over').forEach(x=>x.classList.remove('drag-over'));if(drag){drag.classList.remove('dragging');drag=null}})}
function siteSectionPayload(){const root=$('#siteSectionsEditor');return{order:[...root.querySelectorAll('.section-manager-row')].map(x=>x.dataset.sectionKey),visibility:Object.fromEntries([...root.querySelectorAll('.section-manager-row')].map(x=>[x.dataset.sectionKey,x.querySelector('.section-manager-visible')?.checked!==false]))}}
function fillSettings(){const s=D.settings||{};$$('.setting').forEach(e=>{const k=e.dataset.key;if(k)e.value=s[k]??''});$$('.setting-check').forEach(e=>e.checked=s[e.dataset.key]!==false);$$('.json-setting').forEach(e=>{const k=e.dataset.key;let v=s[k]??[];e.value=typeof v==='string'?v:JSON.stringify(v,null,2)});const all=$('#allSettingsJson');if(all)all.value=JSON.stringify(s,null,2);buildSocialFields();buildCollectionEditors();buildAboutOrderEditor();buildGatewayOrderEditor();buildFlowEditors();buildCmsExtraEditors();buildSiteSectionEditor()}
const social=[['fiverr','Fiverr'],['freelancer','Freelancer'],['linkedin','LinkedIn'],['dribbble','Dribbble'],['behance','Behance'],['github','GitHub'],['whatsapp','WhatsApp'],['email','Email'],['facebook','Facebook'],['instagram','Instagram'],['twitter','X / Twitter'],['upwork','Upwork']];
const socialIconMap={fiverr:'fiverr.svg',freelancer:'freelancer.svg',linkedin:'linkedin.svg',dribbble:'dribbble.svg',behance:'behance.svg',github:'github.svg',whatsapp:'whatsapp.svg',email:'email.svg',facebook:'facebook.svg',instagram:'instagram.svg',twitter:'x-twitter.svg',upwork:'upwork.svg'};
function socialItems(){const s=D.settings||{},custom=Array.isArray(s.customSocialLinks)?s.customSocialLinks:[],overrides=(s.socialIconOverrides&&typeof s.socialIconOverrides==='object')?s.socialIconOverrides:{};const byKey={};social.forEach(([k,l])=>byKey[k]={key:k,label:l,url:String(s[k]||''),icon:String(overrides[k]||''),builtin:true});custom.forEach(x=>{if(x&&x.key)byKey[x.key]={key:String(x.key),label:String(x.label||x.key),url:String(x.url||''),icon:String(x.icon||''),builtin:false}});let order=Array.isArray(s.socialOrder)?s.socialOrder:[];order=[...order,...Object.keys(byKey).filter(k=>!order.includes(k))];return order.map(k=>byKey[k]).filter(x=>x&&x.url)}
function socialIcon(item){const file=socialIconMap[item.key];if(item.icon)return `<img src="${esc(item.icon)}" alt="">`;return file?`<img src="assets/social/${file}" alt="">`:`<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M10 13a5 5 0 0 0 7.1.1l2-2a5 5 0 0 0-7.1-7.1l-1.2 1.2"></path><path d="M14 11a5 5 0 0 0-7.1-.1l-2 2A5 5 0 0 0 12 20l1.2-1.2"></path></svg>`}
function uploadSocialIcon(file){return new Promise((resolve,reject)=>{if(!file)return resolve('');const r=new FileReader();r.onload=async()=>{try{const out=await api('/api/admin/media',{method:'POST',body:JSON.stringify({data:r.result,name:file.name})});resolve(out.url||'')}catch(e){reject(e)}};r.onerror=reject;r.readAsDataURL(file)})}
function trashSvg(){return `<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 7h16M9 7V4.5h6V7M7 7l.8 12.5h8.4L17 7M10 10.5v6M14 10.5v6"></path></svg>`}
function uploadSvg(){return `<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 16V4M7.5 8.5 12 4l4.5 4.5M5 15.5v3A1.5 1.5 0 0 0 6.5 20h11a1.5 1.5 0 0 0 1.5-1.5v-3"></path></svg>`}
function buildSocialFields(){const root=$('#socialFields');if(!root)return;const items=socialItems();root.innerHTML=items.length?items.map(x=>`<div class="social-row" draggable="true" data-social-key="${esc(x.key)}" data-builtin="${x.builtin?'1':'0'}" data-icon-url="${esc(x.icon||'')}"><span class="social-drag" title="Drag to reorder">☷</span><span class="social-icon">${socialIcon(x)}</span><button class="btn social-remove" type="button" data-remove-social="${esc(x.key)}" title="Delete social link" aria-label="Delete social link">${trashSvg()}</button><input class="field social-label" data-key="${esc(x.key)}" value="${esc(x.label)}" placeholder="Name"><input class="field social-url" data-key="${esc(x.key)}" value="${esc(x.url)}" placeholder="Link / URL"><button class="social-icon-upload" type="button" title="Upload SVG / image icon" aria-label="Upload SVG or image icon">${uploadSvg()}<span class="social-upload-label">SVG</span></button><input class="social-icon-file" type="file" accept="image/svg+xml,image/png,image/jpeg,image/webp" hidden></div>`).join(''):'<div class="social-empty">No social links added yet.</div>';bindSocialEditor(root)}
function bindSocialEditor(root){
 if(!root||root.dataset.bound)return;root.dataset.bound='1';let drag=null;
 const clearDrag=()=>{root.querySelectorAll('.drag-over').forEach(x=>x.classList.remove('drag-over'));if(drag){drag.classList.remove('dragging');drag=null}};
 const saveOrder=async()=>{try{const out=await api('/api/admin/settings',{method:'PUT',body:JSON.stringify(readSocialSettings())});D.settings=out;toast('Social position saved ✓')}catch(e){toast(e.message)}};
 root.addEventListener('dragstart',e=>{drag=e.target.closest('.social-row');if(drag){e.dataTransfer.effectAllowed='move';try{e.dataTransfer.setData('text/plain',drag.dataset.socialKey)}catch{}drag.classList.add('dragging')}});
 root.addEventListener('dragover',e=>{const t=e.target.closest('.social-row');if(!drag||!t||t===drag)return;e.preventDefault();t.classList.add('drag-over');const r=t.getBoundingClientRect();root.insertBefore(drag,e.clientY<r.top+r.height/2?t:t.nextSibling)});
 root.addEventListener('drop',async e=>{if(!drag)return;e.preventDefault();clearDrag();await saveOrder()});
 root.addEventListener('dragend',clearDrag);
 root.addEventListener('click',e=>{
   const upload=e.target.closest('.social-icon-upload');
   if(upload){ e.preventDefault(); upload.parentElement?.querySelector('.social-icon-file')?.click(); return; }
   const b=e.target.closest('[data-remove-social]');if(!b)return;
   const key=b.dataset.removeSocial;
   root.querySelector(`.social-row[data-social-key="${CSS.escape(key)}"]`)?.remove();
   if(!root.querySelector('.social-row'))root.innerHTML='<div class="social-empty">No social links added yet.</div>';
 });
 root.addEventListener('change',async e=>{
   const input=e.target.closest('.social-icon-file'); if(!input)return;
   const row=input.closest('.social-row'); const file=input.files?.[0]; if(!row||!file)return;
   if(!/^image\/(svg\+xml|png|jpeg|webp)$/.test(file.type) && !/\.svg$/i.test(file.name)){toast('Please upload an SVG, PNG, JPG or WEBP icon');input.value='';return;}
   try{
     const uploadBtn=row.querySelector('.social-icon-upload'); if(uploadBtn)uploadBtn.disabled=true;
     const url=await uploadSocialIcon(file); if(!url)throw Error('Icon upload failed');
     row.dataset.iconUrl=url;
     const preview=row.querySelector('.social-icon'); if(preview)preview.innerHTML=`<img src="${esc(url)}" alt="">`;
     toast('Social icon uploaded ✓ — save to publish');
   }catch(err){toast(err.message||'Icon upload failed')}
   finally{if(row.querySelector('.social-icon-upload'))row.querySelector('.social-icon-upload').disabled=false;input.value='';}
 });
}
function readSocialSettings(){const root=$('#socialFields');const rows=[...root.querySelectorAll('.social-row')];const out={socialOrder:rows.map(r=>r.dataset.socialKey),customSocialLinks:[],socialIconOverrides:{}};social.forEach(([k])=>out[k]='');rows.forEach(r=>{const key=r.dataset.socialKey,label=r.querySelector('.social-label')?.value.trim()||key,url=r.querySelector('.social-url')?.value.trim()||'',icon=r.dataset.iconUrl||'';const built=social.some(x=>x[0]===key);if(built){out[key]=url;if(icon)out.socialIconOverrides[key]=icon}else out.customSocialLinks.push({key,label,url,icon})});return out}
function buildAboutOrderEditor(){const root=$('#aboutOrderEditor');if(!root)return;const fallback=['photo','content'],order=Array.isArray(D.settings?.aboutLayoutOrder)?D.settings.aboutLayoutOrder.filter(x=>fallback.includes(x)):fallback;const normalized=[...order,...fallback.filter(x=>!order.includes(x))];root.innerHTML=normalized.map((x,i)=>`<div class="collection-row sortable-item about-order-row" draggable="true" data-about-key="${x}"><span class="sortable-handle">Drag</span><div><strong>${x==='photo'?'About Image / Photo':'About Text / Content'}</strong><small class="muted" style="display:block;margin-top:4px;font-size:8px">${x==='photo'?'Left visual block':'Right information + skills block'}</small></div></div>`).join('');bindAboutSortable(root)}
function bindAboutSortable(root){if(!root||root.dataset.sortBound)return;root.dataset.sortBound='1';let item=null;root.addEventListener('dragstart',e=>{item=e.target.closest('.about-order-row');if(item){item.classList.add('dragging');e.dataTransfer.effectAllowed='move'}});root.addEventListener('dragover',e=>{const target=e.target.closest('.about-order-row');if(!item||!target||target===item)return;e.preventDefault();target.classList.add('drag-over');const r=target.getBoundingClientRect();root.insertBefore(item,e.clientY<r.top+r.height/2?target:target.nextSibling)});root.addEventListener('drop',async e=>{if(!item)return;e.preventDefault();root.querySelectorAll('.drag-over').forEach(x=>x.classList.remove('drag-over'));const order=[...root.querySelectorAll('.about-order-row')].map(x=>x.dataset.aboutKey);item.classList.remove('dragging');item=null;sortBusy=true;try{const out=await api('/api/admin/settings',{method:'PUT',body:JSON.stringify({aboutLayoutOrder:order})});D.settings=out;applyAboutLayoutPreview(order);toast('About order saved ✓')}catch(e){toast(e.message);await load()}finally{sortBusy=false}});root.addEventListener('dragend',()=>{root.querySelectorAll('.drag-over').forEach(x=>x.classList.remove('drag-over'));if(item){item.classList.remove('dragging');item=null}})}
function applyAboutLayoutPreview(order){const root=document.querySelector('#aboutOrderEditor');if(!root)return;const seq=Array.isArray(order)?order:['photo','content'];root.innerHTML=seq.map(x=>`<div class="collection-row sortable-item about-order-row" draggable="true" data-about-key="${x}"><span class="sortable-handle">Drag</span><div><strong>${x==='photo'?'About Image / Photo':'About Text / Content'}</strong><small class="muted" style="display:block;margin-top:4px;font-size:8px">${x==='photo'?'Left visual block':'Right information + skills block'}</small></div></div>`).join('');bindAboutSortable(root)}

async function saveSettings(){try{let b={};const all=$('#allSettingsJson');if(all&&all.value.trim()){try{b=JSON.parse(all.value)}catch{throw Error('Advanced A–Z JSON is invalid')}}$$('.setting').forEach(e=>{if(e.dataset.key)b[e.dataset.key]=e.value});$$('.setting-check').forEach(e=>b[e.dataset.key]=e.checked);$$('.json-setting').forEach(e=>{const k=e.dataset.key;try{b[k]=JSON.parse(e.value||'[]')}catch{throw Error('Invalid JSON in '+k)}});if(typeof b.paymentGatewayCurrencyUrls==='string'){try{b.paymentGatewayCurrencyUrls=b.paymentGatewayCurrencyUrls.trim()?JSON.parse(b.paymentGatewayCurrencyUrls):{}}catch{throw Error('Currency-specific gateway URLs must be valid JSON')}}if($('#socialFields'))Object.assign(b,readSocialSettings());
 let f=$('#heroImageFile')?.files?.[0];if(f)b.heroImage=await uploadFile(f,4);let af=$('#aboutImageFile')?.files?.[0];if(af)b.aboutImage=await uploadFile(af,4);let cv=$('#cvFile')?.files?.[0];if(cv)b.heroTertiaryHref=await uploadFile(cv,12);let vf=$('#videoFile')?.files?.[0];if(vf)b.videoUrl=await uploadFile(vf,60);let vp=$('#videoPosterFile')?.files?.[0];if(vp)b.videoPoster=await uploadFile(vp,4);
 const out=await api('/api/admin/settings',{method:'PUT',body:JSON.stringify(b)});D.settings=out;fillSettings();toast('All website changes saved ✓')}catch(e){toast(e.message)}}
async function uploadFile(file,mb){if(file.size>mb*1024*1024)throw Error(`File must be under ${mb}MB`);return new Promise((ok,no)=>{const r=new FileReader;r.onload=async()=>{try{const x=await api('/api/admin/media',{method:'POST',body:JSON.stringify({data:r.result,name:file.name})});ok(x.url)}catch(e){no(e)}};r.onerror=no;r.readAsDataURL(file)})}
const FX_TO_USD={USD:1,GBP:1.34,EUR:1.16,BDT:0.0082};
const CURRENCY_SYMBOL={USD:'$',GBP:'£',EUR:'€',BDT:'৳'};
function money(n,c){const v=(Number(n)||0).toLocaleString('en-US',{minimumFractionDigits:0,maximumFractionDigits:2});return (CURRENCY_SYMBOL[String(c||'USD').toUpperCase()]||'')+v}
function dashboardMoneyMarkup(n,c){const v=(Number(n)||0).toLocaleString('en-US',{minimumFractionDigits:0,maximumFractionDigits:2});const sym=CURRENCY_SYMBOL[String(c||'USD').toUpperCase()]||'';return `<span class="earnings-number"><span class="earnings-symbol">${esc(sym)}</span><span class="earnings-value">${esc(v)}</span></span>`}
function fitEarningsValue(){const row=document.getElementById('statEarnings');const amount=row?.querySelector('.earnings-number');if(!row||!amount)return;const cs=getComputedStyle(row);const max=Math.min(21,parseFloat(cs.fontSize)||21),min=12;const available=Math.max(1,row.clientWidth-(parseFloat(cs.paddingLeft)||0)-(parseFloat(cs.paddingRight)||0));let lo=min,hi=max,best=min;amount.style.fontSize=max+'px';amount.style.letterSpacing='-.035em';for(let i=0;i<20;i++){const mid=(lo+hi)/2;amount.style.fontSize=mid.toFixed(2)+'px';if(amount.scrollWidth<=available){best=mid;lo=mid}else hi=mid}amount.style.fontSize=best.toFixed(2)+'px';}
let earningsFitObserver=null;function bindEarningsFit(){const el=document.getElementById('statEarnings');if(!el||el.dataset.fitBound)return;el.dataset.fitBound='1';if(typeof ResizeObserver==='undefined')return;earningsFitObserver=new ResizeObserver(()=>requestAnimationFrame(fitEarningsValue));earningsFitObserver.observe(el);if(el.parentElement)earningsFitObserver.observe(el.parentElement)}
function toUSD(amount,c){return (Number(amount)||0)*(FX_TO_USD[String(c||'USD').toUpperCase()]||1)}
function fromUSD(amount,c){const code=String(c||'USD').toUpperCase();return (Number(amount)||0)/(FX_TO_USD[code]||1)}
function selectedDashboardCurrency(){return localStorage.getItem('ethonDashboardCurrency')||'USD'}
function paymentTotals(){const rows=(D.messages||[]).filter(x=>x.type==='payment');const out={paidUSD:0,pendingUSD:0,cancelledUSD:0};rows.forEach(x=>{const amount=Number(x.amount||String(x.budget||'').match(/[0-9]+(?:\.[0-9]+)?/)?.[0]||0);const c=String(x.currency||((x.budget||'').match(/USD|GBP|EUR|BDT/)||['USD'])[0]).toUpperCase();const st=x.status||'pending';if(st==='paid')out.paidUSD+=toUSD(amount,c);else if(st==='cancelled')out.cancelledUSD+=toUSD(amount,c);else out.pendingUSD+=toUSD(amount,c)});return out}
function renderVisitorChart(history){const area=$('#chartArea'),line=$('#chartLine'),spark=document.querySelector('.spark path');if(!area||!line)return;const rows=Array.isArray(history)?history.slice(-20):[];if(!rows.length){area.setAttribute('d','M0 130 V150H0Z');line.setAttribute('d','M0 130');return}const vals=rows.map(x=>Number(x.count||0)),min=Math.min(...vals),max=Math.max(...vals),range=Math.max(1,max-min),W=560,H=150,padY=18;const pts=vals.map((v,i)=>{const x=rows.length===1?0:(i/(rows.length-1))*W;const y=H-padY-((v-min)/range)*(H-padY*2);return [x,y]});const d=pts.map((p,i)=>(i?'L':'M')+p[0].toFixed(1)+' '+p[1].toFixed(1)).join(' ');line.setAttribute('d',d);area.setAttribute('d',d+' V150H0Z');if(spark){const sw=120,sh=45;const sd=pts.map((p,i)=>{const x=(i/Math.max(1,pts.length-1))*sw;const y=8+(p[1]/H)*(sh-14);return (i?'L':'M')+x.toFixed(1)+' '+y.toFixed(1)}).join(' ');spark.setAttribute('d',sd)}}
function getMessageStats(){const contacts=(D.messages||[]).filter(x=>x.type!=='payment');const chat=(D.conversations||[]).flatMap(c=>Array.isArray(c.messages)?c.messages:[]).filter(m=>m.channel==='chat'&&m.from==='visitor');return{contactCount:contacts.length,contactUnread:contacts.filter(x=>!x.read).length,chatCount:chat.length,chatUnread:(D.conversations||[]).reduce((n,c)=>n+Number(c.chatUnread||0),0),total:contacts.length+chat.length}}
function renderDashboard(){const p=D.projects||[],m=D.messages||[],s=D.settings||{},v=Number(s.visitorCount||0),cv=Number(s.cvDownloads||0),pv=Number(s.profileViews||0),t=paymentTotals(),q=getMessageStats(),cur=selectedDashboardCurrency();const cvEl=$('#dashboardCurrency');if(cvEl)cvEl.value=cur;const paid=fromUSD(t.paidUSD,cur),pending=fromUSD(t.pendingUSD,cur),cancelled=fromUSD(t.cancelledUSD,cur),total=paid+pending+cancelled;$('#statProjects').textContent=p.length;renderVisitorChart(s.visitorHistory||[]);$('#statVisitors').textContent=v>=1000?(v/1000).toFixed(v>=10000?0:1)+'K':v;$('#statProfileViews').textContent=pv>=1000?(pv/1000).toFixed(1)+'K':pv;$('#statMessages').textContent=q.total;$('#messageBadge').textContent=Math.min(99,q.contactUnread);$('#chatBadge').textContent=Math.min(99,q.chatUnread);$('#statCvDownloads').textContent=cv;$('#statEarnings').innerHTML=dashboardMoneyMarkup(paid,cur);bindEarningsFit();requestAnimationFrame(fitEarningsValue);$('#statEarningsBdt').textContent='Selected currency: '+cur;$('#statVisitorsGrowth').textContent='Live visitor count';$('#statMessagesGrowth').innerHTML=`<span>Contact: ${q.contactCount}</span><i></i><span class="live-chat-count">Live Chat: ${q.chatCount}</span>`;$('#chartVisitors').textContent=v.toLocaleString();$('#chartVisitorsGrowth').textContent='Live tracking';$('#paidSummary').textContent=money(paid,cur);$('#pendingSummary').textContent=money(pending,cur);$('#cancelledSummary').textContent=money(cancelled,cur);$('#paidBdtSummary').textContent=money(total,cur);$('#availableUsd').textContent=money(paid,cur);$('#pendingUsd').textContent=money(pending,cur);$('#availableBdt').textContent=money(paid,cur);$('#recentProjects').innerHTML=p.slice(-4).reverse().map(x=>`<div class="project-row"><img class="project-thumb" src="${esc(x.image||'assets/logo.png')}"><div class="project-copy"><strong>${esc(x.title)}</strong><small><span class="status">${x.published===false?'Hidden':'Published'}</span> &nbsp;•&nbsp; ${esc(x.category||'Project')}</small></div><div class="row-right">${x.live?'↗':''} ${x.featured?'★':''}</div></div>`).join('')||'<p class="muted" style="padding:12px">No projects yet.</p>';$('#recentMessages').innerHTML=m.slice(0,4).map(x=>`<div class="message-row"><div class="avatar" style="display:grid;place-items:center">${esc((x.name||'?').slice(0,1).toUpperCase())}</div><div class="message-copy"><strong>${esc(x.name)}</strong><small>${esc(x.message||'').slice(0,70)}</small></div><div class="message-time">${timeAgo(x.createdAt)}</div><div class="dot"></div></div>`).join('')||'<p class="muted" style="padding:12px">No messages.</p>'}

function timeAgo(ts){if(!ts)return'';const d=(Date.now()-new Date(ts).getTime())/60000;if(d<1)return'now';if(d<60)return Math.round(d)+'m ago';if(d<1440)return Math.round(d/60)+'h ago';return Math.round(d/1440)+'d ago'}
function renderProjects(){const list=$('#projectList');if(!list)return;list.innerHTML=D.projects.map(x=>`<div class="item sortable-item" draggable="true" data-sort-id="${esc(x.id)}"><span class="sortable-handle">Drag</span>${x.image?`<img class="thumb" src="${esc(x.image)}">`:''}<h3>${esc(x.title)}</h3><span class="pill">${esc(x.category||'Project')}</span> <span class="muted" style="font-size:9px">${x.published===false?'Hidden':'Published'}</span><p>${esc(x.description||'')}</p><div class="actions"><button class="btn ghost" onclick="openProject('${x.id}')">Edit</button><button class="btn danger" onclick="del('projects','${x.id}')">Delete</button></div></div>`).join('')||'<p class="muted" style="padding:15px">No projects.</p>';bindSortable(list,'projects')}
function renderTests(){const list=$('#testList');if(!list)return;list.innerHTML=D.testimonials.map(x=>`<div class="item sortable-item" draggable="true" data-sort-id="${esc(x.id)}"><span class="sortable-handle">Drag</span>${x.avatar?`<img class="thumb" src="${esc(x.avatar)}">`:''}<h3>${esc(x.name)}</h3><span class="pill">★ ${Number(x.rating||0).toFixed(1)}</span> <span class="muted" style="font-size:9px">${esc(x.role||'')}</span><p>${esc(x.text||'')}</p><div class="actions"><button class="btn ghost" onclick="openTestimonial('${x.id}')">Edit</button><button class="btn danger" onclick="del('testimonials','${x.id}')">Delete</button></div></div>`).join('')||'<p class="muted" style="padding:15px">No testimonials.</p>';bindSortable(list,'testimonials')}
function renderServices(){let s=D.settings?.services||[];const root=$('#serviceList');root.innerHTML=s.map((x,i)=>`<div class="item sortable-item" draggable="true" data-sort-index="${i}"><span class="sortable-handle">Drag</span><h3>${esc(x.title)}</h3><span class="pill">${x.enabled===false?'Hidden':'Visible'}</span><p>${esc(x.description||'')}</p><div class="actions"><button class="btn ghost" onclick="editService(${i})">Edit</button><button class="btn danger" onclick="removeService(${i})">Delete</button></div></div>`).join('')||'<p class="muted" style="padding:15px">No services.</p>';bindServiceSortable(root)}
function bindServiceSortable(root){if(!root||root.dataset.sortBound)return;root.dataset.sortBound='1';let item=null;root.addEventListener('dragstart',e=>{item=e.target.closest('.sortable-item');if(item){item.classList.add('dragging');e.dataTransfer.effectAllowed='move'}});root.addEventListener('dragover',e=>{const target=e.target.closest('.sortable-item');if(!item||!target||target===item)return;e.preventDefault();target.classList.add('drag-over');const r=target.getBoundingClientRect();root.insertBefore(item,e.clientY<r.top+r.height/2?target:target.nextSibling)});root.addEventListener('drop',async e=>{if(!item)return;e.preventDefault();root.querySelectorAll('.drag-over').forEach(x=>x.classList.remove('drag-over'));const services=D.settings?.services||[];const order=[...root.querySelectorAll('.sortable-item')].map(x=>Number(x.dataset.sortIndex));const reordered=order.map(i=>services[i]).filter(Boolean);item.classList.remove('dragging');item=null;sortBusy=true;try{const out=await api('/api/admin/settings',{method:'PUT',body:JSON.stringify({services:reordered})});D.settings=out;renderServices();toast('Service order saved ✓')}catch(err){toast(err.message);await load()}finally{sortBusy=false}});root.addEventListener('dragend',()=>{root.querySelectorAll('.drag-over').forEach(x=>x.classList.remove('drag-over'));if(item){item.classList.remove('dragging');item=null}})}
function buildGatewayOrderEditor(){const root=$('#gatewayOrderEditor');if(!root)return;const fallback=['STRIPE','PAYPAL','PAYONEER','GOOGLE PAY','BINANCE PAY','BKASH'];const labels={STRIPE:'Stripe (Card)',PAYPAL:'PayPal',PAYONEER:'Payoneer','GOOGLE PAY':'Google Pay','BINANCE PAY':'Binance Pay',BKASH:'bKash'};const order=Array.isArray(D.settings?.paymentGatewayOrder)?D.settings.paymentGatewayOrder.filter(x=>fallback.includes(x)):fallback;const normalized=[...order,...fallback.filter(x=>!order.includes(x))];root.innerHTML=normalized.map(x=>`<div class="collection-row sortable-item gateway-order-row" draggable="true" data-gateway-key="${x}"><span class="sortable-handle">Drag</span><div><strong>${labels[x]||x}</strong></div></div>`).join('');bindGatewaySortable(root)}
function bindGatewaySortable(root){if(!root||root.dataset.sortBound)return;root.dataset.sortBound='1';let item=null;root.addEventListener('dragstart',e=>{item=e.target.closest('.gateway-order-row');if(item){item.classList.add('dragging');e.dataTransfer.effectAllowed='move'}});root.addEventListener('dragover',e=>{const target=e.target.closest('.gateway-order-row');if(!item||!target||target===item)return;e.preventDefault();target.classList.add('drag-over');const r=target.getBoundingClientRect();root.insertBefore(item,e.clientY<r.top+r.height/2?target:target.nextSibling)});root.addEventListener('drop',async e=>{if(!item)return;e.preventDefault();root.querySelectorAll('.drag-over').forEach(x=>x.classList.remove('drag-over'));const order=[...root.querySelectorAll('.gateway-order-row')].map(x=>x.dataset.gatewayKey);item.classList.remove('dragging');item=null;sortBusy=true;try{const out=await api('/api/admin/settings',{method:'PUT',body:JSON.stringify({paymentGatewayOrder:order})});D.settings=out;toast('Gateway order saved ✓')}catch(err){toast(err.message);await load()}finally{sortBusy=false}});root.addEventListener('dragend',()=>{root.querySelectorAll('.drag-over').forEach(x=>x.classList.remove('drag-over'));if(item){item.classList.remove('dragging');item=null}})}
function renderMessages(){const l=$('#messageList');l.innerHTML=(D.messages||[]).map(x=>`<div class="message-row"><div class="message-copy"><strong>${esc(x.name)} <span class="pill">${esc(x.type||'contact')}</span></strong><small>${esc(x.email)} ${x.phone?'• '+esc(x.phone):''} • ${esc(x.service||'')}</small><small style="color:#b6becb;margin-top:5px">${esc(x.message)}</small></div><div class="message-time">${timeAgo(x.createdAt)}</div><button class="btn ghost" onclick="markRead('${x.id}')">${x.read?'Read':'Mark read'}</button></div>`).join('')||'<p class="muted" style="padding:14px">No messages.</p>'}
async function markRead(id){await api('/api/admin/messages/'+id,{method:'PATCH',body:JSON.stringify({read:true})});await load();tab('messages');toast('Message marked read')}
function renderChats(){const l=$('#chatList');l.innerHTML=(D.conversations||[]).map(x=>`<div class="chat-user ${activeChat===x.id?'active':''}" onclick="selectChat('${x.id}')"><strong>${esc(x.name)} ${Number(x.chatUnread||0)>0?`<span class="pill" style="float:right">${Math.min(99,Number(x.chatUnread||0))} new</span>`:''}</strong><small>${esc(x.email)} • ${timeAgo(x.updatedAt)}</small></div>`).join('')||'<p class="muted" style="padding:10px">No conversations yet.</p>'}
async function selectChat(id){activeChat=id;const c=(D.conversations||[]).find(x=>x.id===id);$('#chatHeader h2').textContent=c?c.name:'Conversation';try{const ms=await api('/api/chat/'+id);$('#chatMessages').innerHTML=ms.map(m=>{const isAdmin=m.from==='admin',at=Array.isArray(m.attachments)?m.attachments:[],files=at.map(x=>`<div class="chat-attachment"><a href="/api/chat/file?file=${encodeURIComponent(String(x.url||'').replace(/^\/uploads\//,'').replace(/^.*[?]file=/,'').replace(/^.*[?]file=/,''))}" target="_blank" rel="noopener">↗ ${esc(x.name)}</a><a class="chat-attachment-download" href="/api/chat/download?file=${encodeURIComponent(String(x.url||'').replace(/^\/uploads\//,'').replace(/^.*[?]file=/,''))}" download title="Download file" aria-label="Download file"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 3v11m0 0 4-4m-4 4-4-4M5 18.5h14"/></svg></a></div>`).join('');return `<div class="chat-message-row ${isAdmin?'admin-row':'visitor-row'}"><div class="bubble ${isAdmin?'admin':''}">${m.text?esc(m.text):''}${files}<div style="opacity:.45;font-size:8px;margin-top:3px">${new Date(m.createdAt).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}</div></div><img class="chat-msg-avatar" src="${isAdmin?'assets/ethon-admin-avatar.webp':'assets/chat-ghost-avatar.svg'}" alt="${isAdmin?'Ethon':'Client'}"></div>`}).join('');$('#chatMessages').scrollTop(1e9);await api('/api/admin/conversations/'+id+'/read',{method:'POST'});if(c)c.chatUnread=0;renderDashboard()}catch{}renderChats()}
async function renderTransactions(){const rows=(D.messages||[]).filter(x=>x.type==='payment');$('#transactionList').innerHTML=rows.map(x=>{const st=x.status||'pending';return `<div class="message-row"><div class="message-copy"><strong>${esc(x.name)} <span class="pill">${esc(x.paymentMethod||'PAYMENT')}</span> <span class="pill">${esc(st.toUpperCase())}</span></strong><small>${esc(x.email)} • ${esc(x.budget||'')}</small><small style="color:#b6becb">${esc(x.message)}</small></div><div class="message-time">${timeAgo(x.createdAt)}</div><div class="actions"><a class="btn" target="_blank" rel="noopener" href="/payment-voucher.html?id=${encodeURIComponent(x.id)}">Voucher</a><button class="btn green" onclick="setPaymentStatus('${x.id}','paid')">Mark Paid</button><button class="btn danger" onclick="setPaymentStatus('${x.id}','cancelled')">Cancel</button></div></div>`}).join('')||'<p class="muted" style="padding:14px">No payment requests yet.</p>'}
async function setPaymentStatus(id,status){await api('/api/admin/messages/'+id,{method:'PATCH',body:JSON.stringify({status})});await load();tab('transactions');toast(status==='paid'?'Payment marked paid ✓':'Payment cancelled')}
async function persistOrder(type,items){sortBusy=true;try{await api('/api/admin/'+type+'/reorder',{method:'POST',body:JSON.stringify({ids:items.map(x=>x.id)})});toast('Order saved ✓')}catch(e){toast(e.message);await load()}finally{sortBusy=false}}
function bindSortable(root,type){if(!root||root.dataset.sortBound)return;root.dataset.sortBound='1';root.addEventListener('dragstart',e=>{const item=e.target.closest('.sortable-item');if(!item)return;dragState={type,item};item.classList.add('dragging');e.dataTransfer.effectAllowed='move';e.dataTransfer.setData('text/plain',item.dataset.sortId||'')});root.addEventListener('dragover',e=>{const item=e.target.closest('.sortable-item');if(!item||!dragState||dragState.type!==type||item===dragState.item)return;e.preventDefault();item.classList.add('drag-over');const r=item.getBoundingClientRect();root.insertBefore(dragState.item,e.clientY<r.top+r.height/2?item:item.nextSibling)});root.addEventListener('drop',async e=>{if(!dragState||dragState.type!==type)return;e.preventDefault();root.querySelectorAll('.drag-over').forEach(x=>x.classList.remove('drag-over'));const ids=[...root.querySelectorAll('.sortable-item')].map(x=>String(x.dataset.sortId));const source=type==='projects'?D.projects:D.testimonials;const ordered=ids.map(id=>source.find(x=>String(x.id)===id)).filter(Boolean);if(type==='projects')D.projects=ordered;else D.testimonials=ordered;const item=dragState.item;dragState=null;item.classList.remove('dragging');await persistOrder(type,ordered);renderDashboard()});root.addEventListener('dragend',()=>{root.querySelectorAll('.drag-over').forEach(x=>x.classList.remove('drag-over'));if(dragState?.item){dragState.item.classList.remove('dragging');dragState=null}})}
function bindSkillSortable(root){if(!root||root.dataset.sortBound)return;root.dataset.sortBound='1';root.addEventListener('dragstart',e=>{const item=e.target.closest('.sortable-item');if(!item)return;dragState={type:'skills',item};item.classList.add('dragging');e.dataTransfer.effectAllowed='move'});root.addEventListener('dragover',e=>{const item=e.target.closest('.sortable-item');if(!item||!dragState||dragState.type!=='skills'||item===dragState.item)return;e.preventDefault();item.classList.add('drag-over');const r=item.getBoundingClientRect();root.insertBefore(dragState.item,e.clientY<r.top+r.height/2?item:item.nextSibling)});root.addEventListener('drop',async e=>{if(!dragState||dragState.type!=='skills')return;e.preventDefault();root.querySelectorAll('.drag-over').forEach(x=>x.classList.remove('drag-over'));const value=readCollection('skillsEditor','skills');const names=[...root.querySelectorAll('.sortable-item')].map(r=>r.dataset.sortKey);const reordered=names.map(n=>value.find(x=>x.name===n)).filter(Boolean);const item=dragState.item;dragState=null;item.classList.remove('dragging');sortBusy=true;try{const out=await api('/api/admin/settings',{method:'PUT',body:JSON.stringify({skills:reordered})});D.settings=out;toast('Skills order saved ✓')}catch(e){toast(e.message);await load()}finally{sortBusy=false}});root.addEventListener('dragend',()=>{root.querySelectorAll('.drag-over').forEach(x=>x.classList.remove('drag-over'));if(dragState?.item){dragState.item.classList.remove('dragging');dragState=null}})}
function formHtml(type,x={}){if(type==='service')return `<input type="hidden" id="eid" value="${esc(x.id||'')}"><label>Service title<input class="field" id="titlef" required value="${esc(x.title||'')}"></label><label>Description<textarea class="field" id="desc">${esc(x.description||'')}</textarea></label><label><input id="enabled" type="checkbox" ${x.enabled!==false?'checked':''}> Visible on website</label><button class="btn" style="margin-top:10px">Save service</button>`;if(type==='project')return `<input type="hidden" id="eid" value="${esc(x.id||'')}"><div class="form-grid"><label>Title<input class="field" id="titlef" required value="${esc(x.title||'')}"></label><label>Category<input class="field" id="cat" value="${esc(x.category||'')}"></label><label>Role<input class="field" id="role" value="${esc(x.role||'')}"></label><label>Case study URL<input class="field" id="case" value="${esc(x.caseStudy||'')}"></label><label class="full">Description<textarea class="field" id="desc">${esc(x.description||'')}</textarea></label><label>Live URL<input class="field" id="live" value="${esc(x.live||'')}"></label><label>Cover image<input id="img" class="field" type="file" accept="image/*"></label><label><input id="featured" type="checkbox" ${x.featured?'checked':''}> Featured</label><label><input id="published" type="checkbox" ${x.published!==false?'checked':''}> Published</label></div><button class="btn" style="margin-top:10px">Save project</button>`;return `<input type="hidden" id="eid" value="${esc(x.id||'')}"><div class="form-grid"><label>Client name<input class="field" id="titlef" required value="${esc(x.name||'')}"></label><label>Professional title / Role<input class="field" id="role" value="${esc(x.role||'')}"></label><label>Rating<input class="field" id="rating" type="number" min="1" max="5" step=".1" value="${x.rating??4.9}"></label><label>Location<input class="field" id="location" value="${esc(x.location||'')}"></label><label>Avatar<input id="img" class="field" type="file" accept="image/*"></label><label>Flag SVG URL<input class="field" id="flagSvg" value="${esc(x.flagSvg||'')}"></label><label class="full">Testimonial<textarea class="field" id="desc" required>${esc(x.text||'')}</textarea></label><label class="full"><input id="published" type="checkbox" ${x.published!==false?'checked':''}> Published</label></div><button class="btn" style="margin-top:10px">Save testimonial</button>`}
function openProject(id){const x=D.projects.find(p=>p.id===id)||{};$('#modalTitle').textContent=id?'Edit Project':'Add Project';$('#entityForm').innerHTML=formHtml('project',x);$('#entityForm').onsubmit=e=>saveEntity(e,'project');$('#modal').classList.add('open')}
function openTestimonial(id){const x=D.testimonials.find(t=>t.id===id)||{};$('#modalTitle').textContent=id?'Edit Testimonial':'Add Testimonial';$('#entityForm').innerHTML=formHtml('test',x);$('#entityForm').onsubmit=e=>saveEntity(e,'test');$('#modal').classList.add('open')}
function editService(i){const x=(D.settings.services||[])[i]||{};$('#modalTitle').textContent='Edit Service';$('#entityForm').innerHTML=formHtml('service',x);$('#entityForm').onsubmit=async e=>{e.preventDefault();let arr=[...(D.settings.services||[])];arr[i]={title:$('#titlef').value,description:$('#desc').value,enabled:$('#enabled').checked};await api('/api/admin/settings',{method:'PUT',body:JSON.stringify({services:arr})});closeModal();await load();toast('Service updated')}}
function removeService(i){if(!confirm('Delete this service?'))return;let arr=[...(D.settings.services||[])];arr.splice(i,1);api('/api/admin/settings',{method:'PUT',body:JSON.stringify({services:arr})}).then(()=>{load();toast('Service deleted')})}
function openService(){openServiceAdd()};function openServiceAdd(){$('#modalTitle').textContent='Add Service';$('#entityForm').innerHTML=formHtml('service',{});$('#entityForm').onsubmit=async e=>{e.preventDefault();let arr=[...(D.settings.services||[])];arr.push({title:$('#titlef').value,description:$('#desc').value,enabled:$('#enabled').checked});await api('/api/admin/settings',{method:'PUT',body:JSON.stringify({services:arr})});closeModal();await load();toast('Service added')}}
async function saveEntity(e,type){e.preventDefault();try{const id=$('#eid').value;let b={},f=$('#img')?.files?.[0];if(type==='project')b={title:$('#titlef').value,category:$('#cat').value,role:$('#role').value,description:$('#desc').value,caseStudy:$('#case').value,live:$('#live').value,featured:$('#featured').checked,published:$('#published').checked};else b={name:$('#titlef').value,role:$('#role').value,text:$('#desc').value,rating:Number($('#rating').value),location:$('#location').value,flagSvg:$('#flagSvg').value,published:$('#published').checked};if(f){b.imageData=await dataUrl(f);b.imageName=f.name}const path='/api/admin/'+(type==='project'?'projects':'testimonials');await api(path+(id?'/'+id:''),{method:id?'PUT':'POST',body:JSON.stringify(b)});closeModal();await load();toast('Saved successfully')}catch(e){toast(e.message)}}
function dataUrl(f){return new Promise((ok,no)=>{const r=new FileReader;r.onload=()=>ok(r.result);r.onerror=no;r.readAsDataURL(f)})}
async function del(type,id){if(!confirm('Delete this item?'))return;await api('/api/admin/'+type+'/'+id,{method:'DELETE'});await load();toast('Deleted')}
function closeModal(){$('#modal').classList.remove('open')}
function bindMarqueeSortable(root){if(!root||root.dataset.sortBound)return;root.dataset.sortBound='1';root.addEventListener('dragstart',e=>{const item=e.target.closest('.sortable-item');if(!item)return;dragState={type:'marquee',item};item.classList.add('dragging');e.dataTransfer.effectAllowed='move'});root.addEventListener('dragover',e=>{const item=e.target.closest('.sortable-item');if(!item||!dragState||dragState.type!=='marquee'||item===dragState.item)return;e.preventDefault();item.classList.add('drag-over');const r=item.getBoundingClientRect();root.insertBefore(dragState.item,e.clientY<r.top+r.height/2?item:item.nextSibling)});root.addEventListener('drop',async e=>{if(!dragState||dragState.type!=='marquee')return;e.preventDefault();root.querySelectorAll('.drag-over').forEach(x=>x.classList.remove('drag-over'));const value=readCollection('marqueeEditor','marquee');const ids=[...root.querySelectorAll('.sortable-item')].map(r=>r.dataset.sortKey);const reordered=ids.map(k=>value.find(x=>x.id===k)).filter(Boolean);const item=dragState.item;dragState=null;item.classList.remove('dragging');sortBusy=true;try{const out=await api('/api/admin/settings',{method:'PUT',body:JSON.stringify({marqueeLogos:reordered})});D.settings=out;toast('Logo order saved ✓')}catch(e){toast(e.message);await load()}finally{sortBusy=false}});root.addEventListener('dragend',()=>{root.querySelectorAll('.drag-over').forEach(x=>x.classList.remove('drag-over'));if(dragState?.item){dragState.item.classList.remove('dragging');dragState=null}})}
function collectionRows(id,items,type){const root=$('#'+id);if(!root)return;root.innerHTML='';if(!items||!items.length){root.innerHTML='<div class="collection-empty">No items yet. Add your first item below.</div>';return}items.forEach((x,i)=>{const row=document.createElement('div');row.className='collection-row'+(type==='skills'||type==='marquee'?' sortable-item':'');if(type==='skills'){row.draggable=true;row.dataset.sortIndex=i;row.dataset.sortKey=x.name||'';row.innerHTML=`<span class="sortable-handle">Drag</span><div><span class="mini-label">Skill name</span><input class="field c-name" value="${esc(x.name||'')}"></div><div><span class="mini-label">Description</span><input class="field c-desc" value="${esc(x.description||'')}"></div><div class="percent"><span class="mini-label">Percent</span><input class="field c-percent" type="number" min="0" max="100" value="${Number(x.percent||0)}"></div><button class="btn remove" type="button">Remove</button>`}else if(type==='nav')row.innerHTML=`<div><span class="mini-label">Label</span><input class="field c-label" value="${esc(x.label||'')}"></div><div><span class="mini-label">Link / anchor</span><input class="field c-href" value="${esc(x.href||'')}"></div><div class="switch-wrap"><input class="switch c-enabled" type="checkbox" ${x.enabled!==false?'checked':''}> Visible</div><button class="btn remove" type="button">Remove</button>`;else if(type==='marquee'){row.draggable=true;row.dataset.sortIndex=i;row.dataset.sortKey=x.id||('ml'+i);row.innerHTML=`<span class="sortable-handle">Drag</span><img class="marquee-thumb" src="${esc(x.logo||'')}" alt="" style="width:44px;height:44px;object-fit:contain;background:rgba(255,255,255,.04);border-radius:8px;border:1px solid rgba(255,255,255,.08)"><div><span class="mini-label">Company name</span><input class="field c-name" value="${esc(x.name||'')}"></div><div style="flex:1.6"><span class="mini-label">Logo image / SVG URL</span><input class="field c-logo" value="${esc(x.logo||'')}"></div><div class="switch-wrap"><input class="switch c-enabled" type="checkbox" ${x.enabled!==false?'checked':''}> Visible</div><button class="btn remove" type="button">Remove</button>`;row.querySelector('.c-logo').addEventListener('input',e=>{row.querySelector('.marquee-thumb').src=e.target.value})}else row.innerHTML=`<div><span class="mini-label">Value</span><input class="field c-value" value="${esc(x.value||'')}"></div><div><span class="mini-label">Label</span><input class="field c-label" value="${esc(x.label||'')}"></div><div></div><button class="btn remove" type="button">Remove</button>`;row.querySelector('.remove').onclick=()=>{items.splice(i,1);collectionRows(id,items,type)};root.appendChild(row)});if(type==='skills')bindSkillSortable(root);if(type==='marquee')bindMarqueeSortable(root)}
function readCollection(id,type){return [...document.querySelectorAll('#'+id+' .collection-row')].map((r,i)=>type==='skills'?{name:r.querySelector('.c-name').value.trim(),description:r.querySelector('.c-desc').value.trim(),percent:Number(r.querySelector('.c-percent').value||0)}:type==='nav'?{label:r.querySelector('.c-label').value.trim(),href:r.querySelector('.c-href').value.trim(),enabled:r.querySelector('.c-enabled').checked}:type==='marquee'?{id:r.dataset.sortKey||('ml'+i),name:r.querySelector('.c-name').value.trim(),logo:r.querySelector('.c-logo').value.trim(),enabled:r.querySelector('.c-enabled').checked}:{value:r.querySelector('.c-value').value.trim(),label:r.querySelector('.c-label').value.trim()}).filter(x=>type==='skills'?x.name:type==='nav'?x.label:type==='marquee'?(x.name||x.logo):x.label)}

function buildSimpleListEditor(rootId,items,kind){const root=$('#'+rootId);if(!root)return;root.innerHTML='';(items||[]).forEach((x,i)=>{const r=document.createElement('div');r.className='collection-row sortable-item';r.draggable=true;r.dataset.i=i;r.innerHTML=`<span class="sortable-handle">Drag</span><div style="flex:1"><span class="mini-label">${kind==='faq'?'Question':'Point'}</span><input class="field x-text" value="${esc(kind==='faq'?(x.question||''):(x.text||''))}"></div>${kind==='faq'?`<div style="flex:1.5"><span class="mini-label">Answer</span><textarea class="field x-answer">${esc(x.answer||'')}</textarea></div>`:''}<div class="switch-wrap"><input class="switch x-enabled" type="checkbox" ${x.enabled!==false?'checked':''}> Visible</div><button class="btn remove x-remove" type="button">Remove</button>`;r.querySelector('.x-remove').onclick=()=>{items.splice(i,1);buildSimpleListEditor(rootId,items,kind)};root.appendChild(r)});bindCmsListSortable(rootId,items,kind)}
function bindCmsListSortable(rootId,items,kind){const root=$('#'+rootId);if(!root||root.dataset.bound)return;root.dataset.bound='1';let drag=null;root.addEventListener('dragstart',e=>{drag=e.target.closest('.sortable-item');if(drag){drag.classList.add('dragging');e.dataTransfer.effectAllowed='move'}});root.addEventListener('dragover',e=>{const t=e.target.closest('.sortable-item');if(!drag||!t||t===drag)return;e.preventDefault();const r=t.getBoundingClientRect();root.insertBefore(drag,e.clientY<r.top+r.height/2?t:t.nextSibling)});root.addEventListener('drop',e=>{if(!drag)return;e.preventDefault();const rows=[...root.querySelectorAll('.sortable-item')];const reordered=rows.map(r=>items[Number(r.dataset.i)]);items.splice(0,items.length,...reordered);rows.forEach((r,i)=>r.dataset.i=i);drag.classList.remove('dragging');drag=null});root.addEventListener('dragend',()=>{if(drag){drag.classList.remove('dragging');drag=null}})}
function readSimpleList(rootId,kind){return [...document.querySelectorAll('#'+rootId+' .collection-row')].map(r=>kind==='faq'?{id:'faq'+Math.random().toString(36).slice(2,8),question:r.querySelector('.x-text').value.trim(),answer:r.querySelector('.x-answer').value.trim(),enabled:r.querySelector('.x-enabled').checked}:{id:'cmp'+Math.random().toString(36).slice(2,8),text:r.querySelector('.x-text').value.trim(),enabled:r.querySelector('.x-enabled').checked}).filter(x=>kind==='faq'?(x.question&&x.answer):x.text)}
function buildCompareEditor(){const c=D.settings?.compareContent||{};const l=c.left||{},r=c.right||{};['compareTitleField','compareDescriptionField','compareLeftTitle','compareLeftSubtitle','compareRightTitle','compareRightSubtitle'].forEach(id=>{const e=$('#'+id);if(e)e.value=id==='compareTitleField'?(D.settings.compareTitle||''):id==='compareDescriptionField'?(D.settings.compareDescription||''):id==='compareLeftTitle'?(l.title||''):id==='compareLeftSubtitle'?(l.subtitle||''):id==='compareRightTitle'?(r.title||''):r.subtitle||''});buildSimpleListEditor('compareLeftEditor',JSON.parse(JSON.stringify(l.items||[])),'compare');buildSimpleListEditor('compareRightEditor',JSON.parse(JSON.stringify(r.items||[])),'compare')}
function buildFaqEditor(){const a=JSON.parse(JSON.stringify(D.settings?.faqItems||[]));const t=$('#faqTitleField'),d=$('#faqDescriptionField');if(t)t.value=D.settings?.faqTitle||'';if(d)d.value=D.settings?.faqDescription||'';buildSimpleListEditor('faqEditor',a,'faq')}
function buildCmsExtraEditors(){buildCompareEditor();buildFaqEditor()}
function buildCollectionEditors(){collectionRows('skillsEditor',JSON.parse(JSON.stringify(D.settings?.skills||[])),'skills');collectionRows('navEditor',JSON.parse(JSON.stringify(D.settings?.navItems||[])),'nav');collectionRows('metricsEditor',JSON.parse(JSON.stringify(D.settings?.metrics||[])),'metrics');collectionRows('marqueeEditor',JSON.parse(JSON.stringify(D.settings?.marqueeLogos||[])),'marquee');const mf=$('#marqueeEyebrowField');if(mf)mf.value=D.settings?.marqueeEyebrow||''}
function buildFlowEditors(){
  const ptf=$('#processTitleField');if(ptf)ptf.value=D.settings?.processTitle||'';
  const pdf=$('#processDescField');if(pdf)pdf.value=D.settings?.processDescription||'';
  renderProcessEditor(JSON.parse(JSON.stringify(D.settings?.processSteps||[])));
  renderMetricsEditor2(JSON.parse(JSON.stringify(D.settings?.metrics||[])));
  renderEstimatorEditor(JSON.parse(JSON.stringify(D.settings?.estimatorGroups||[])));
}
function bindSimpleSortable(root,type,saveKey){if(!root||root.dataset.flowSortBound)return;root.dataset.flowSortBound='1';let dragged=null;root.addEventListener('dragstart',e=>{const x=e.target.closest('[draggable="true"]');if(!x)return;dragged=x;x.classList.add('dragging');e.dataTransfer.effectAllowed='move'});root.addEventListener('dragover',e=>{const x=e.target.closest('[draggable="true"]');if(!dragged||!x||x===dragged)return;e.preventDefault();x.classList.add('drag-over');const r=x.getBoundingClientRect();root.insertBefore(dragged,e.clientY<r.top+r.height/2?x:x.nextSibling)});root.addEventListener('dragend',()=>{root.querySelectorAll('.drag-over').forEach(x=>x.classList.remove('drag-over'));if(dragged){dragged.classList.remove('dragging');dragged=null}})}
function renderProcessEditor(items){const root=$('#processEditor');if(!root)return;root.innerHTML=(items||[]).map((x,i)=>`<div class="flow-group process-edit" draggable="true" data-index="${i}"><div class="flow-group-head"><span class="flow-drag">↕</span><div><span class="mini-label">Title</span><input class="field p-title" value="${esc(x.title||'')}"></div><div><span class="mini-label">Step</span><input class="field p-step" value="${i+1}" readonly></div><div><span class="mini-label">Description</span><input class="field p-desc" value="${esc(x.description||'')}"></div><button class="btn remove p-remove" type="button">Remove</button></div></div>`).join('')||'<div class="collection-empty">No process cards yet.</div>';root.querySelectorAll('.p-remove').forEach(b=>b.onclick=()=>{b.closest('.process-edit').remove()});bindSimpleSortable(root,'process','processSteps')}
function readProcessEditor(){return [...document.querySelectorAll('#processEditor .process-edit')].map((r,i)=>({title:r.querySelector('.p-title').value.trim(),description:r.querySelector('.p-desc').value.trim()})).filter(x=>x.title)}
function renderMetricsEditor2(items){const root=$('#metricsEditor2');if(!root)return;root.innerHTML=(items||[]).map((x,i)=>`<div class="flow-group metric-edit" draggable="true"><div class="flow-group-head"><span class="flow-drag">↕</span><div><span class="mini-label">Value</span><input class="field m-value" value="${esc(x.value||'')}"></div><div style="grid-column:span 2"><span class="mini-label">Label</span><input class="field m-label" value="${esc(x.label||'')}"></div><button class="btn remove m-remove" type="button">Remove</button></div></div>`).join('')||'<div class="collection-empty">No metrics yet.</div>';root.querySelectorAll('.m-remove').forEach(b=>b.onclick=()=>b.closest('.metric-edit').remove());bindSimpleSortable(root,'metrics','metrics')}
function readMetricsEditor2(){return [...document.querySelectorAll('#metricsEditor2 .metric-edit')].map(r=>({value:r.querySelector('.m-value').value.trim(),label:r.querySelector('.m-label').value.trim()})).filter(x=>x.label)}
function renderEstimatorEditor(groups){const root=$('#estimatorEditor');if(!root)return;root.innerHTML=(groups||[]).map((g,gi)=>`<div class="flow-group estimator-edit" draggable="true" data-group-index="${gi}" data-group-id="${esc(g.id||("group"+gi))}"><div class="flow-group-head"><span class="flow-drag">↕</span><div><span class="mini-label">Group title</span><input class="field e-title" value="${esc(g.title||'')}"></div><div><span class="mini-label">Mode</span><select class="field e-mode"><option value="single" ${g.mode==='single'?'selected':''}>Single</option><option value="multi" ${g.mode==='multi'?'selected':''}>Multi</option></select></div><div><span class="mini-label">Summary label</span><input class="field e-summary" value="${esc(g.summaryLabel||'')}"></div><button class="btn remove e-remove" type="button">Remove</button></div><div class="flow-options">${(g.options||[]).map((o,oi)=>`<div class="flow-option" draggable="true"><span class="flow-drag">↕</span><div><span class="mini-label">Option label</span><input class="field o-label" value="${esc(o.label||'')}"></div><div><span class="mini-label">Price</span><input class="field o-price" type="number" step="0.01" value="${o.price??''}"></div><div><span class="mini-label">Multiplier</span><input class="field o-mult" type="number" step="0.01" value="${o.mult??''}"></div><div><span class="mini-label">Add-on</span><input class="field o-add" type="number" step="0.01" value="${o.add??''}"></div><button class="btn remove o-remove" type="button">Remove</button><input class="field o-days flow-wide" placeholder="Days e.g. 10–14" value="${esc(o.days||'')}"></div>`).join('')}</div><button class="btn ghost flow-add e-add-option" type="button">＋ Add Option</button></div>`).join('')||'<div class="collection-empty">No estimator groups yet.</div>';root.querySelectorAll('.e-remove').forEach(b=>b.onclick=()=>b.closest('.estimator-edit').remove());root.querySelectorAll('.o-remove').forEach(b=>b.onclick=()=>b.closest('.flow-option').remove());root.querySelectorAll('.e-add-option').forEach(b=>b.onclick=()=>{const box=b.previousElementSibling;const r=document.createElement('div');r.className='flow-option';r.draggable=true;r.innerHTML='<span class="flow-drag">↕</span><div><span class="mini-label">Option label</span><input class="field o-label" value="New Option"></div><div><span class="mini-label">Price</span><input class="field o-price" type="number"></div><div><span class="mini-label">Multiplier</span><input class="field o-mult" type="number" step="0.01"></div><div><span class="mini-label">Add-on</span><input class="field o-add" type="number"></div><button class="btn remove o-remove" type="button">Remove</button><input class="field o-days flow-wide" placeholder="Days e.g. 10–14">';r.querySelector('.o-remove').onclick=()=>r.remove();box.appendChild(r);bindNestedSortable(box)});root.querySelectorAll('.flow-options').forEach(bindNestedSortable);bindSimpleSortable(root,'estimator','estimatorGroups')}
function bindNestedSortable(root){if(root.dataset.sortBound)return;root.dataset.sortBound='1';let d=null;root.addEventListener('dragstart',e=>{d=e.target.closest('.flow-option');if(d){d.classList.add('dragging');e.dataTransfer.effectAllowed='move'}});root.addEventListener('dragover',e=>{const t=e.target.closest('.flow-option');if(!d||!t||t===d)return;e.preventDefault();t.classList.add('drag-over');const r=t.getBoundingClientRect();root.insertBefore(d,e.clientY<r.top+r.height/2?t:t.nextSibling)});root.addEventListener('dragend',()=>{root.querySelectorAll('.drag-over').forEach(x=>x.classList.remove('drag-over'));if(d){d.classList.remove('dragging');d=null}})}
function readEstimatorEditor(){return [...document.querySelectorAll('#estimatorEditor .estimator-edit')].map((g,gi)=>({id:g.dataset.groupId||('group'+gi),title:g.querySelector('.e-title').value.trim(),mode:g.querySelector('.e-mode').value,summaryLabel:g.querySelector('.e-summary').value.trim(),options:[...g.querySelectorAll('.flow-option')].map((o,oi)=>{const v=(sel)=>o.querySelector(sel).value.trim();const x={id:(g.dataset.groupId||'g')+'-'+oi,label:v('.o-label')};const p=v('.o-price'),m=v('.o-mult'),a=v('.o-add'),days=v('.o-days');if(p)x.price=Number(p);if(m)x.mult=Number(m);if(a)x.add=Number(a);if(days)x.days=days;return x}).filter(x=>x.label)})) .filter(x=>x.title)}

async function saveVisualCollection(key,id,type){const value=readCollection(id,type);await api('/api/admin/settings',{method:'PUT',body:JSON.stringify({[key]:value})});await load();toast('Changes saved ✓')}
async function load(){D=await api('/api/admin/overview');renderDashboard();renderProjects();renderTests();renderServices();fillSettings();renderMessages();renderTransactions()}
$$('[data-range-select]').forEach(sel=>sel.addEventListener('change',()=>$$('[data-range-select]').forEach(other=>{other.value=sel.value})));
document.getElementById('dashboardCurrency')?.addEventListener('change',e=>{localStorage.setItem('ethonDashboardCurrency',e.target.value);renderDashboard()});
document.getElementById('addSocialVisual')?.addEventListener('click',()=>{const root=$('#socialFields');if(!root)return;const key='custom_'+Date.now();const row=document.createElement('div');row.className='social-row';row.draggable=true;row.dataset.socialKey=key;row.dataset.builtin='0';row.dataset.iconUrl='';row.innerHTML=`<span class="social-drag">☷</span><span class="social-icon"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 5v14M5 12h14"></path></svg></span><button class="btn social-remove" type="button" data-remove-social="${key}" title="Delete social link" aria-label="Delete social link">${trashSvg()}</button><input class="field social-label" data-key="${key}" value="" placeholder="Name"><input class="field social-url" data-key="${key}" value="" placeholder="Link / URL"><button class="social-icon-upload" type="button" title="Upload SVG / image icon" aria-label="Upload SVG or image icon">${uploadSvg()}<span class="social-upload-label">SVG</span></button><input class="social-icon-file" type="file" accept="image/svg+xml,image/png,image/jpeg,image/webp" hidden>`;root.querySelector('.social-empty')?.remove();root.appendChild(row);row.querySelector('.social-label')?.focus()});
document.getElementById('saveSocialVisual')?.addEventListener('click',async()=>{try{const out=await api('/api/admin/settings',{method:'PUT',body:JSON.stringify(readSocialSettings())});D.settings=out;buildSocialFields();toast('Social links saved ✓');window.dispatchEvent(new Event('ethon:social-updated'))}catch(e){toast(e.message)}});
$('#socialFields')?.addEventListener('click',e=>{const b=e.target.closest('.social-icon-upload');if(b){b.nextElementSibling?.click();}}); $('#socialFields')?.addEventListener('change',async e=>{const f=e.target.closest('.social-icon-file');if(!f||!f.files?.[0])return;const row=f.closest('.social-row');try{const url=await uploadSocialIcon(f.files[0]);if(!url)throw new Error('Icon upload returned no URL.');row.dataset.iconUrl=url;const box=row.querySelector('.social-icon');if(url)box.innerHTML=`<img src="${esc(url)}" alt="">`;toast('Icon uploaded ✓')}catch(err){toast(err.message)}finally{f.value='';}});
$$('.side-nav button[data-tab]').forEach(b=>b.addEventListener('click',()=>tab(b.dataset.tab)));$$('[data-tab-target]').forEach(b=>b.addEventListener('click',()=>tab(b.dataset.tabTarget)));$$('[data-action="project"]').forEach(b=>b.addEventListener('click',()=>openProject('')));$$('[data-action="testimonial"]').forEach(b=>b.addEventListener('click',()=>openTestimonial('')));$$('[data-action="service"]').forEach(b=>b.addEventListener('click',openServiceAdd));$$('[data-save-settings]').forEach(b=>b.addEventListener('click',saveSettings));$('#modalClose').onclick=closeModal;$('#modal').addEventListener('click',e=>{if(e.target.id==='modal')closeModal()});$('#refreshMessages').onclick=async()=>{await load();renderMessages();toast('Messages refreshed')};$('#refreshTransactions').onclick=async()=>{await load();renderTransactions();toast('Transactions refreshed')};$('#logout').onclick=async()=>{await api('/api/admin/logout',{method:'POST'});location.reload()};const chatFiles=$('#chatFiles'),chatAttach=$('#chatAttach'),chatAttachList=$('#chatAttachList');let adminSelectedFiles=[];const renderChatAttach=()=>{if(!chatAttachList)return;chatAttachList.innerHTML=adminSelectedFiles.map((f,i)=>`<span>${esc(f.name)} <button type="button" data-remove="${i}">×</button></span>`).join('')};chatAttach?.addEventListener('click',()=>chatFiles?.click());chatFiles?.addEventListener('change',()=>{adminSelectedFiles=Array.from(chatFiles.files||[]).slice(0,5);renderChatAttach()});chatAttachList?.addEventListener('click',e=>{const b=e.target.closest('[data-remove]');if(b){adminSelectedFiles.splice(Number(b.dataset.remove),1);renderChatAttach()}});const readAdminFile=f=>new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve({name:f.name,type:f.type,size:f.size,data:r.result});r.onerror=reject;r.readAsDataURL(f)});$('#chatForm').onsubmit=async e=>{e.preventDefault();if(!activeChat)return toast('Select a conversation');const text=$('#chatInput').value.trim();if(!text&&!adminSelectedFiles.length)return;const btn=$('#chatForm button[type="submit"]');btn.disabled=true;try{const attachments=await Promise.all(adminSelectedFiles.map(readAdminFile));await api('/api/admin/conversations/'+activeChat,{method:'POST',body:JSON.stringify({text,attachments})});$('#chatInput').value='';adminSelectedFiles=[];if(chatFiles)chatFiles.value='';renderChatAttach();await selectChat(activeChat)}catch(err){toast(err.message)}finally{btn.disabled=false}};
$('#loginForm').onsubmit=async e=>{e.preventDefault();$('#loginError').textContent='';try{await api('/api/admin/login',{method:'POST',body:JSON.stringify({password:$('#password').value})});$('#login').classList.add('hidden');$('#app').classList.remove('hidden');await load();tab('dashboard')}catch(err){$('#loginError').textContent=err.message}};

document.getElementById('addFaq')?.addEventListener('click',()=>{const a=readSimpleList('faqEditor','faq');a.push({id:'faq'+Date.now(),question:'New question',answer:'Write the answer here.',enabled:true});buildSimpleListEditor('faqEditor',a,'faq')});
document.getElementById('saveFaq')?.addEventListener('click',async()=>{try{const out=await api('/api/admin/settings',{method:'PUT',body:JSON.stringify({faqItems:readSimpleList('faqEditor','faq'),faqTitle:$('#faqTitleField')?.value||'',faqDescription:$('#faqDescriptionField')?.value||''})});D.settings=out;buildCmsExtraEditors();toast('FAQ saved ✓')}catch(e){toast(e.message)}});
document.getElementById('addCompareLeft')?.addEventListener('click',()=>{const a=readSimpleList('compareLeftEditor','compare');a.push({id:'cmp'+Date.now(),text:'New point',enabled:true});buildSimpleListEditor('compareLeftEditor',a,'compare');});
document.getElementById('addCompareRight')?.addEventListener('click',()=>{const a=readSimpleList('compareRightEditor','compare');a.push({id:'cmp'+Date.now(),text:'New point',enabled:true});buildSimpleListEditor('compareRightEditor',a,'compare');});
document.getElementById('saveCompare')?.addEventListener('click',async()=>{try{const c=D.settings?.compareContent||{};const out=await api('/api/admin/settings',{method:'PUT',body:JSON.stringify({compareTitle:$('#compareTitleField')?.value||'',compareDescription:$('#compareDescriptionField')?.value||'',compareContent:{left:{title:$('#compareLeftTitle')?.value||'',subtitle:$('#compareLeftSubtitle')?.value||'',items:readSimpleList('compareLeftEditor','compare')},right:{title:$('#compareRightTitle')?.value||'',subtitle:$('#compareRightSubtitle')?.value||'',items:readSimpleList('compareRightEditor','compare')}}})});D.settings=out;buildCmsExtraEditors();toast('Compare section saved ✓')}catch(e){toast(e.message)}});
document.getElementById('saveSiteSections')?.addEventListener('click',async()=>{try{const p=siteSectionPayload();const out=await api('/api/admin/site-sections',{method:'PUT',body:JSON.stringify(p)});D.settings={...D.settings,sectionOrder:out.order,sectionVisibility:out.visibility};buildSiteSectionEditor();toast('Website layout saved ✓')}catch(e){toast(e.message)}});
document.getElementById('passwordForm')?.addEventListener('submit',async e=>{e.preventDefault();const hint=document.getElementById('passwordHint');const current=document.getElementById('currentPassword').value;const next=document.getElementById('newPassword').value;const confirm=document.getElementById('confirmPassword').value;if(next!==confirm){if(hint)hint.textContent='New passwords do not match.';return}try{await api('/api/admin/password',{method:'POST',body:JSON.stringify({currentPassword:current,newPassword:next})});if(hint)hint.textContent='Password changed. Signing out…';setTimeout(()=>location.reload(),700)}catch(err){if(hint)hint.textContent=err.message}});
document.getElementById('saveAboutOrder')?.addEventListener('click',async()=>{const root=document.getElementById('aboutOrderEditor');if(!root)return;const order=[...root.querySelectorAll('.about-order-row')].map(x=>x.dataset.aboutKey);try{const out=await api('/api/admin/settings',{method:'PUT',body:JSON.stringify({aboutLayoutOrder:order})});D.settings=out;toast('About order saved ✓')}catch(e){toast(e.message)}});
document.getElementById('saveGatewayOrder')?.addEventListener('click',async()=>{const root=document.getElementById('gatewayOrderEditor');if(!root)return;const order=[...root.querySelectorAll('.gateway-order-row')].map(x=>x.dataset.gatewayKey);try{const out=await api('/api/admin/settings',{method:'PUT',body:JSON.stringify({paymentGatewayOrder:order})});D.settings=out;toast('Gateway order saved ✓')}catch(e){toast(e.message)}});document.getElementById('addSkillVisual')?.addEventListener('click',()=>{const items=readCollection('skillsEditor','skills');items.push({name:'',description:'',percent:80});collectionRows('skillsEditor',items,'skills')});document.getElementById('saveSkillsVisual')?.addEventListener('click',()=>saveVisualCollection('skills','skillsEditor','skills'));document.getElementById('addNavVisual')?.addEventListener('click',()=>{const items=readCollection('navEditor','nav');items.push({label:'New item',href:'#',enabled:true});collectionRows('navEditor',items,'nav')});document.getElementById('saveNavVisual')?.addEventListener('click',()=>saveVisualCollection('navItems','navEditor','nav'));document.getElementById('addMetricVisual')?.addEventListener('click',()=>{const items=readCollection('metricsEditor','metrics');items.push({value:'0',label:'New metric'});collectionRows('metricsEditor',items,'metrics')});document.getElementById('saveMetricsVisual')?.addEventListener('click',()=>saveVisualCollection('metrics','metricsEditor','metrics'));document.getElementById('addMarqueeVisual')?.addEventListener('click',()=>{const items=readCollection('marqueeEditor','marquee');items.push({id:'ml'+Date.now(),name:'New Company',logo:'',enabled:true});collectionRows('marqueeEditor',items,'marquee')});document.getElementById('saveMarqueeVisual')?.addEventListener('click',async()=>{try{const value=readCollection('marqueeEditor','marquee');const eyebrow=$('#marqueeEyebrowField')?.value||'';const out=await api('/api/admin/settings',{method:'PUT',body:JSON.stringify({marqueeLogos:value,marqueeEyebrow:eyebrow})});D.settings=out;await load();toast('Logos saved ✓')}catch(e){toast(e.message)}});
document.getElementById('addProcessVisual')?.addEventListener('click',()=>{const a=readProcessEditor();a.push({title:'New Step',description:'Describe this process step.'});renderProcessEditor(a)});document.getElementById('saveProcessVisual')?.addEventListener('click',async()=>{try{const pt=$('#processTitleField')?.value||'';const pd=$('#processDescField')?.value||'';await api('/api/admin/settings',{method:'PUT',body:JSON.stringify({processSteps:readProcessEditor(),processTitle:pt,processDescription:pd})});await load();toast('Process saved ✓')}catch(e){toast(e.message)}});document.getElementById('addMetricVisual2')?.addEventListener('click',()=>{const a=readMetricsEditor2();a.push({value:'0',label:'New Metric'});renderMetricsEditor2(a)});document.getElementById('saveMetricsVisual2')?.addEventListener('click',async()=>{try{await api('/api/admin/settings',{method:'PUT',body:JSON.stringify({metrics:readMetricsEditor2()})});await load();toast('Metrics saved ✓')}catch(e){toast(e.message)}});document.getElementById('addEstimatorGroup')?.addEventListener('click',()=>{const a=readEstimatorEditor();a.push({id:'group'+Date.now(),title:'New Estimator Group',mode:'single',summaryLabel:'Select an option',options:[{id:'new',label:'New Option',price:0}]});renderEstimatorEditor(a)});document.getElementById('saveEstimatorVisual')?.addEventListener('click',async()=>{try{const a=readEstimatorEditor();a.forEach((g,i)=>{if(!g.id||g.id.startsWith('group'))g.id=['category','scope','turnaround','extras'][i]||('group'+i)});await api('/api/admin/settings',{method:'PUT',body:JSON.stringify({estimatorGroups:a})});await load();toast('Estimator saved ✓')}catch(e){toast(e.message)}});
(async()=>{try{await api('/api/admin/overview');$('#login').classList.add('hidden');$('#app').classList.remove('hidden');await load();tab('dashboard')}catch{}})();
setInterval(async()=>{if(sortBusy||dragState||document.hidden||document.getElementById('app')?.classList.contains('hidden'))return;try{D=await api('/api/admin/overview');renderDashboard();renderMessages();renderTransactions();if(document.getElementById('chat')?.classList.contains('active')){renderChats();if(activeChat)await selectChat(activeChat)}}catch{}} ,4000);
